// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"mall/internal/user/middleware/jwt"
	"mall/internal/user/repository"
	"mall/internal/user/repository/cache"
	"mall/internal/user/repository/dao"
	"mall/internal/user/service"
	"mall/internal/user/web"
)

// Injectors from wire.go:

func InitGin() *gin.Engine {
	tokenHandler := jwt.NewJwtHandler()
	cmdable := InitRedis()
	redisSession := jwt.NewRedisSession(cmdable)
	v := InitGinMiddlewares(tokenHandler, redisSession)
	db := InitDB()
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository, redisSession)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, tokenHandler)
	engine := InitWeb(v, userHandler)
	return engine
}

// wire.go:

var BaseSet = wire.NewSet(InitRedis, InitDB)
