// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"mall/internal/auth/jwt"
	"mall/internal/product"
	"mall/internal/user"
)

// Injectors from wire.go:

func InitGin() *gin.Engine {
	tokenHandler := jwt.NewJwtHandler()
	cmdable := InitRedis()
	redisSession := jwt.NewRedisSession(cmdable)
	logger := InitLogger()
	v := InitMiddleware(tokenHandler, redisSession, logger)
	db := InitDB(logger)
	userHandler := user.InitUserHandler(db, cmdable)
	productHandler := product.InitProductHandler(db, cmdable)
	engine := InitWeb(v, userHandler, productHandler)
	return engine
}

// wire.go:

var BaseSet = wire.NewSet(InitRedis, InitDB)
