// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"mall/repository"
	"mall/repository/dao"
	"mall/service"
	"mall/web"
)

// Injectors from wire.go:

func InitGin() *gin.Engine {
	db := InitDB()
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	engine := InitWeb(userHandler)
	return engine
}

// wire.go:

var BaseSet = wire.NewSet(InitRedis, InitDB)
