// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"mall/internal/product/repository"
	"mall/internal/product/repository/cache"
	"mall/internal/product/repository/dao"
	"mall/internal/product/service"
	"mall/internal/product/web"
)

// Injectors from wire.go:

func InitProductHandler(db *gorm.DB, cmd redis.Cmdable) *web.ProductHandler {
	productDao := dao.NewProductDao(db)
	productCache := cache.NewProductCache(cmd)
	productRepository := repository.NewProductRepository(productDao, productCache)
	productService := service.NewProductService(productRepository)
	productHandler := web.NewProductHandler(productService)
	return productHandler
}

// wire.go:

var productSet = wire.NewSet(dao.NewProductDao, cache.NewProductCache, repository.NewProductRepository, service.NewProductService, web.NewProductHandler)
