// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cart

import (
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"mall/internal/cart/repository"
	"mall/internal/cart/repository/dao"
	"mall/internal/cart/service"
	"mall/internal/cart/web"
	"mall/internal/product"
)

// Injectors from wire.go:

func NewCartHandler(db *gorm.DB, cmd redis.Cmdable) *web.CartHandler {
	cartDao := dao.NewCartDao(db)
	cartRepository := repository.NewCartRepository(cartDao)
	productRepository := product.NewProductRepository(db, cmd)
	cartService := service.NewCartService(cartRepository, productRepository)
	cartHandler := web.NewCartHandler(cartService)
	return cartHandler
}
